parameters:
    glory_oauth.http_client.class: Buzz\Client\Curl
    glory_oauth.storage.session.class: HWI\Bundle\OAuthBundle\OAuth\RequestDataStorage\SessionStorage
    glory_oauth.ownermap.class: Glory\Bundle\OAuthBundle\OAuth\OwnerMap

services:
    glory_oauth.http_client:
        class: %glory_oauth.http_client.class%
    glory_oauth.storage.session:
        class: %glory_oauth.storage.session.class%
        public: false
        arguments: [@session]
    glory_oauth.ownermap:
        class: %glory_oauth.ownermap.class%
        abstract: true
        arguments: [@security.http_utils, ~, []]
        calls:
            - [setContainer,[@service_container]]
        
